-- AlterTable
ALTER TABLE "Employee" ADD COLUMN     "hra" DOUBLE PRECISION,
ADD COLUMN     "otherAllowance" DOUBLE PRECISION,
ADD COLUMN     "pf" DOUBLE PRECISION,
ADD COLUMN     "pt" DOUBLE PRECISION;
